<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>A library for accessing Atlassians Confluence from .NET</Description>
    <TargetFrameworks>netstandard2.0;net480;net10.0</TargetFrameworks>
    <PackageTags>atlassian;confluence;dapplo</PackageTags>
  </PropertyGroup>
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapplo.HttpExtensions" Version="2.0.11" />
    <PackageReference Include="Dapplo.HttpExtensions.JsonNet" Version="2.0.11" />
  </ItemGroup>
</Project>